### PR TITLE
added svg-sprite generation

### PR DESCRIPTION
**Pull request by Profesor08**
Added generation of svg sprite. It is very useful to target icons by their names without including styles, fonts and class names for elements, and to not worry about font size.

### CODE REVIEW

**Comment by misolori** [comment]
👋  Appreciate the PR, though not sure if we have a need for this and a little concerned about adding another dependency. Do you mind explaining why the current files don't work for you?

**Comment by Profesor08** [comment]
> 👋 Appreciate the PR, though not sure if we have a need for this and a little concerned about adding another dependency. Do you mind explaining why the current files don't work for you?

Almost all icon packs provide different ways to use icons and svg sprite is one of them. Using icons as font put you to work with them as text, it is more difficult to control size and alignment.

**Comment by misolori** [comment]
Had to make some changes to our dependencies (upgraded `fantasticon` & removed `npm-force-resolutions`). Do you mind resolving conflicts so I can test this? Thanks.

**Comment by Profesor08** [comment]
> Had to make some changes to our dependencies (upgraded `fantasticon` & removed `npm-force-resolutions`). Do you mind resolving conflicts so I can test this? Thanks.

resolved

**Comment by misolori** [comment]
Tested this out locally and it's looking great!

CleanShot 2021-10-04 at 11 39 11@2x

Is there any way to allow multiple references to the same icon? We have a [code pointer file](https://github.com/microsoft/vscode-codicons/blob/main/src/template/mapping.json) that can map multiple references to the same icon so it would be nice to still support that.

**Comment by Profesor08** [comment]
> Is there any way to allow multiple references to the same icon?

It is not posible to target one symbol with different ids. Only way is to build sprite manualy with script. I have added a script.

**Comment by misolori** [comment]
This looks perfect, thanks for adding that functionality in!

CleanShot 2021-10-04 at 13 53 00@2x

**Comment by misolori** [comment]
Update the readme with an example for using the svg sprites:

https://github.com/microsoft/vscode-codicons#using-svg-sprites

CleanShot 2021-10-04 at 14 30 13@2x

**Pull request merged**
