### PR TITLE
Add logo-vscode

### PR DESCRIPTION
**Pull request by daviddossett**
Adds the VS Code logo to address the ask in [this issue](https://github.com/microsoft/vscode/issues/131297).

CleanShot 2021-08-23 at 13 35 38@2x

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
We should probably review with CELA first before we include the brand in this repo. I can start a thread.

**Comment by daviddossett** [comment]
> We should probably review with CELA first before we include the brand in this repo. I can start a thread. Please don't merge before we get the green light from them.

Sounds good, thank you! Holding on merging anyway until Miguel is back in town

**Comment by misolori** [comment]
After discussing in https://github.com/microsoft/vscode/issues/131297#issuecomment-909272014 we're going to hold off on adding this for now. Thanks @daviddossett for jumping in so quickly and it's great to know that we have CELA approval to have this added in the future when another occasion arises.

**Comment by daviddossett** [comment]
Makes sense to me 🙏 Thanks for following up on the main issue!

**Pull request closed without merging**
