### PR TITLE
Update question icon

### LINKED ISSUE #159: Icon `question` is not aligned in the center
**Describe the bug**

The icon [`question`](https://github.com/microsoft/vscode-codicons/blob/main/src/icons/question.svg) is not center-aligned.

**To Reproduce**
1. Look at the `question` icon:

image

The icon is not center-aligned

**Expected behavior**

The icon should be center-aligned.

**Screenshots**

image

It should be:

image

**Environment**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by fanzeyi**
Fix #159

### CODE REVIEW

**Comment by fanzeyi** [comment]
@microsoft-github-policy-service agree

**Comment by hbons** [comment]
Thanks for your contribution! It seems that some circled icons that have centred content are intentionally offset to prevent blurriness at lower resolution screens. But there are also some circled icons that are properly centred. So these won't mix well when used together. We should come up with a solution that works for all these icons @daviddossett.

**Comment by troy351** [comment]
@hbons I also found `trash` icon which is not circled but not center aligned

**Comment by hbons** [comment]
Tracking in #243

**Pull request closed without merging**
