### PR TITLE
Update `git-commit` icon

### PR DESCRIPTION
**Pull request by daviddossett**
Updates `git-commit` to feature a centered vertical stroke and slightly thicker circle stroke. This enables the icon to be in proper alignment with the `circle-outline` icon that it's now paired with in the Timeline view.

CleanShot 2022-04-26 at 09 16 43@2x

### CODE REVIEW

**Comment by misolori** [comment]
Hmm...my concern is that it's another similar icon and people looking at the icons might not know why they are different. We run into this issue with the debugger play button (which is thicker) and the regular play button. 

Did you try updating the `git-commit` to have the same weight and positioning instead?

**Comment by daviddossett** [comment]
Yeah, I definitely share the concern. One challenge with updating `git-commit` to use the outline from `circle-outline` is the inherent offset used in `git-commit` to visually center the 1px vertical stroke. It would end up looking something like this:

CleanShot 2022-04-22 at 13 07 52@2x

**Comment by misolori** [comment]
I see that problem, even though we would want to have everything aligned to the pixel grid as much as possible, the vertical line would need to be adjusted and be off-grid. I think I'd rather have that instead of introducing another similar icon.

And backstory on the thicker stroke, the circle outline was actually used only for unverified breakpoints and so the entire breakpoint icons have a slight thicker stroke to stand out in smaller sizes. I think we're a bit inconsistent with this style and can see updating other places where they aren't.

**Review by misolori — APPROVED** [review]
LGTM, do you think we should also update the line to be the same stroke weight? also realize that this might make the rest of the git icons a bit inconsistent so not sure if it's worth it 

CleanShot 2022-04-26 at 10 29 30@2x

**Comment by misolori** [comment]
Feel free to update the codicons file on the vscode repo

**Comment by daviddossett** [comment]
Updated codicons file: https://github.com/microsoft/vscode/commit/dc58d4e2d0abde25dd55f588c3fd6e09a67e54b5

**Pull request merged**
