### PR TITLE
Preview redesign

### PR DESCRIPTION
**Pull request by SNDST00M**
**Is your icon request related to a problem? Please describe.**
Preview icon has a design far too specific to documentation or textual files. This probably stems from the original design rationale for the icon, which was first used in [`./extensions/markdown-language-features`@`microsoft/vscode`](https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features)

**Describe the solution you'd like**
This pull redesigns the `preview.svg` asset and makes it generic, not Markdown-specific.
It also makes the original icon available under the name `document-preview`.

**Describe alternatives you've considered**
Implement SVG previews in vscode core using [`preview.svg`@`40014cd`](https://github.com/microsoft/vscode-codicons/blob/40014cd/src/icons/preview.svg) icon which is too specific to Markdown. Pople assume it's not for previewing an SVG..

**Additional context**

codicons-preview-redesign-before

codicons-preview-redesign-after

### CODE REVIEW

**Comment by misolori** [comment]
Hey, thanks for the PR. Is there an original issue that has more context? It would be helpful to see a visual example of what you are proposing, I had to go into the PR to find the SVGs. 

We do already have a similar icon called `open-preview` that looks similar to your proposal:

CleanShot 2021-06-08 at 10 15 54@2x

**Comment by 4086606** [comment]
The similarity's by design! `open-preview` is meant for the `markdown.showPreviewToSide` command. That icon has two "views" with a dividing "gutter" line.

One would expect `preview` to have an outer path similar to `file-code` and `go-to-file`, because it's used in the Quick Bar.
But no dice - it's got this "newspaper" kind of design, like a document with embedded images.

## Preview of changes

codicons-preview-redesign-before

codicons-preview-redesign-after

**Comment by misolori** [comment]
The reason it looks like a document with embedded images is because it's intended to show that it renders text and images, which come from markdown. That's the only usage we have in the product, so I'm not sure I am understand the problem here.

**Comment by 4086606** [comment]
I am working on SVG preview support in core. It would be nice to have the `preview` icon generic before then.

**Comment by misolori** [comment]
Do you have a link to that work in core?

**Comment by 4086606** [comment]
There is only https://github.com/microsoft/vscode/issues/124901 so far. If you need this work as a pull request, I'm happy to convert this to a draft for <1wk.

**Comment by misolori** [comment]
We first need support of this in core before we add new icons, especially if we're proposing to change the default.

**Comment by 4086606** [comment]
Yeah QA and development will take weeks guaranteed.
I'll be downgrading this to draft for now, thanks for the prompt replies!

**Comment by SNDST00M** [comment]
The SVG preview pull was rejected on account of the issue only having 10 upvotes.
If the icon is useful, you're welcome to add it to the repository

**Pull request closed without merging**
