### PR TITLE
Profile icons

### PR DESCRIPTION
**Pull request by hbons**
New profile icons: image

Small gear icon overlay for when a custom profile icon is set:
image

### CODE REVIEW

**Comment by daviddossett** [comment]
Could you re-share what the small gear looks like and how it would be used? The rest look good—that one was the only one that caught my eye.

**Comment by hbons** [comment]
@daviddossett we'd like to use it as an overlay for the custom profile icon:

image

It's less noisy than the outline version and helps indicate the item is still the original gear menu.

**Comment by hbons** [comment]
Also added mic-filled to this to avoid merge conflicts. 
image

**Comment by hbons** [comment]
I'll make new PRs for these.

**Pull request closed without merging**
