### PR TITLE
Add magnet icon

### PR DESCRIPTION
**Pull request by piersdeseilligny**
My extension ([betterfountain](https://github.com/piersdeseilligny/betterfountain)) needed a magnet icon, so I thought I would submit it as a pull request, as it is a fairly generic icon which could be useful to other extension authors too:
image

I've made sure it respects the style of the other icons and is correctly aligned to the grid, so there shouldn't be any issues. However it isn't included in the `dist` folder, as I wasn't able to actually build this (as there's still a few issues when trying to build on a Windows machine)

### CODE REVIEW

**Review by misolori — APPROVED** [review]
👏 Thanks so much for this PR! You did this perfectly matching the grid + angles. I'll add the build files and then will merge this in shortly 🍻 

Feel free to file an issue for your Windows build issues and will see if I can fix those.

**Comment by misolori** [comment]
This is now in version [`0.0.10`](https://github.com/microsoft/vscode-codicons/releases/tag/0.0.10) and will be available on [Insiders](https://code.visualstudio.com/insiders/) on Monday, as well as part of the September release. Available now via the [npm module](https://www.npmjs.com/package/vscode-codicons).

**Comment by piersdeseilligny** [comment]
Amazing, thank you !

**Review by gardmkdg1 — COMMENTED** [review]
https://guides.github.com/feed/index.xml

**Comment by gardmkdg1** [comment]
https://guides.github.com/feed/index.xml

**Pull request merged**
