### PR TITLE
Add new map-vertical and map-vertical-filled icons

### PR DESCRIPTION
**Pull request by hbons**
Vertical variants of the map icon: `map-vertical` and `map-vertical-filled`.

Also add  `fold-*` mappings and `map-horizontal-*` mappings to the original `map` for consistency.

image

Related: #238

### CODE REVIEW

**Review by dbaeumer — APPROVED** [review]

**Comment by daviddossett** [comment]
What are these for? I think the original map icon is intended for source maps or something. @connor4312 would know.

**Comment by connor4312** [comment]
Source maps use the compass icon

**Comment by daviddossett** [comment]
Ah, my bad. Hallucinating :D

**Comment by hbons** [comment]
[Notebooks](https://github.com/microsoft/vscode-codicons/issues/238) wants it, and the diff viewer uses it to toggle unchanged lines:

image

I thought it would be good to have a vertical version as it matches the direction. :)

**Comment by hbons** [comment]
@daviddossett we might want to use GitHub style collapse/expand icons in the future: 
image
image

**Comment by daviddossett** [comment]
That notebooks issue links to the run-in-section issue. Is that intended? Not sure how it relates to the regions toggle above. Agreed that the map icon doesn't convey the command very well though. I think something like the GH example would make more sense.

**Comment by hbons** [comment]
seems we have these already: 
image

**Pull request merged**
